apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loonflow-log-pvc
  namespace: ops
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi

