# Generated by Django 2.2.12 on 2021-07-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loondept',
            name='label',
            field=models.CharField(blank=True, default='', help_text='因为部门信息一般是从别处同步过来， 为保证对应关系，同步时可以在此字段设置其他系统中相应的唯一标识', max_length=1024, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='loonrole',
            name='label',
            field=models.CharField(blank=True, default='{}', help_text='因为角色信息也可能是从别处同步过来， 为保证对应关系，同步时可以在此字段设置其他系统中相应的唯一标识,字典的json格式', max_length=1024, verbose_name='标签'),
        ),
    ]
