# Generated by Django 2.2.12 on 2021-08-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210726_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='loonuser',
            name='feishu_avatar',
            field=models.TextField(blank=True, null=True, verbose_name='飞书头像'),
        ),
        migrations.AddField(
            model_name='loonuser',
            name='qywechat_avatar',
            field=models.TextField(blank=True, null=True, verbose_name='企业微信头像'),
        ),
    ]
